---
output:
  ioslides_presentation: default
  output: default
author: "HACHEMI-Ali"
date: "29 novembre 2020"
title: 'Developing Data Products : R Markdown Presentation & Plotly'
subtitle: Please use Right/Down Arrow or Space to advance to the next slide. This
  Presentation has 2 slides.
---

```{r setup, include=FALSE,message=FALSE,warning=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	cache = TRUE,
	tidy = TRUE,
	tidy.opts = list(width.cutoff = 60)
)
```
## Synopsis {.smaller}

Following instructions have been given for the assignment -   
1. Create a web page presentation using R Markdown that features a plot created with Plotly.  
2. Host your webpage on either RPubs, GitHub Pages, or NeoCities.   
3. Your webpage must contain the date that you created the document, and it must contain a plot created with Plotly.








```{r}
library(plotly)
```

```{r}
p <- plot_ly(midwest, x = ~percollege, color = ~state, type = "box")
p
```

## Thank You!
